### ISSUE TITLE
preMousePress Callback Broken

### ISSUE THREAD

**Issue by Cernous** [Neko-Box-Coder/filemanager2#1]
Idk if this plugin is still being maintained & I understand that this is a fork of a fork of the original filemanager plugin from the micro 2.0 updated plugins repository.

I believe that the `function preMousePress` may be deprecated as `event` is not being passed (`nil`)  causing an exception to be caught by the editor.

### **To replicate it:**
- micro version: 2.0.15-dev
   - Commit hash: 04c57704
- filemanager2 version: 1.2.2

1. Open up the filemanager2
2. Manually click on a file/folder
3. Exception!

``` shell
Plugin filemanager2: filemanager2:1141: attempt to index a non-table object(nil) with key 'Position'
stack traceback:
        filemanager2:1141: in main chunk
        [G]: ?
Press enter to continue
```

### **Possible workaround:**
I am not adept enough in lua or even knowledgeable to which callbacks do what exactly. Therefore, I won't create a PR for this because I think it's jank.
```lua
-- On click, open at the click's y
-- change "preMousePress" to "onMousePress" instead on line 1141 and drop "event" param
function onMousePress(view)
    if view == tree_view then
      -- Getting the Y position directly from tree_view as cursor will be placed to the location MousePress
      -- Previously, there was a workaround to eliminate effects of softwarp, but in my case skipping these steps entirely seems to cause no issue
      local y = tree_view.Cursor.Loc.Y
      -- Opens the folder, directory at y position
      try_open_at_y(y)
      return false
   end
end
```

Anyways, great work on the nerdfont icons!

**Comment by Neko-Box-Coder** [comment]
Yes, this is still being maintained. I do plan to add a few more features to it but don't have time at the moment. 

Thanks for letting me know about this since I have always used the keyboard to navigate instead of the mouse, never knew there was a bug on this.

Your change is good so I applied it. Thanks for suggesting the change, it saved me some time. It should now be fixed in `v1.2.4`
